### ISSUE TITLE
Language translate doesn't work for summary sensors

### ISSUE THREAD

**Issue by Spirituss** [alexander0042/pirate-weather-ha#100]
The language param is defined in the integration settings. Most of sensors have the states translated into choosen language, but the sensors "summary", "hourly summary", "daily summary" have no translation.

**Comment by alexander0042** [comment]
This is on my list, but is unfortunately a pretty large change. Once i have text summaries working, [this library](https://github.com/darkskyapp/translations) will let me translate them into a ton of languages, but that's still in progress. 
Sorry I don't have a better answer at the moment, but it is on the roadmap!

**Comment by alexander0042** [comment]
Just to keep things tidy, I'm going to merge this issue with [issue #48 in the main repo](https://github.com/alexander0042/pirateweather/issues/48). It's a work in progress, but follow along there for any updates!
