### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by S10XtremeNLow** [alexander0042/pirate-weather-ha#101]
Looks like amiable.io is giving the wrong keys again or something is up. I've tried regenerating and the HACS add-on still says invalid api key.

**Comment by alexander0042** [comment]
Oh shoot, sorry about that. I’ll investigate it now!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: S10XtremeNLow ***@***.***>
Sent: Tuesday, April 11, 2023 7:30:21 AM
To: alexander0042/pirate-weather-ha ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alexander0042/pirate-weather-ha] Invalid API Key (Issue #101)


Looks like amiable.io is giving the wrong keys again or something is up. I've tried regenerating and the HACS add-on still says invalid api key.

**Comment by S10XtremeNLow** [comment]
Wow, talk about a fast response! Thanks!

**Comment by S10XtremeNLow** [comment]
Just sent you an email

**Comment by frakman1** [comment]
It's not working for me either.
From https://pirate-weather.apiable.io/
I created an account with Apiable, created a team, and subscribed to the free weather service. I did it twice and both API keys were rejected

<img width="591" alt="image" src="https://github.com/alexander0042/pirate-weather-ha/assets/5826484/a74e0139-0992-4d86-98ab-646b6a6b6e43">


<img width="459" alt="image" src="https://github.com/alexander0042/pirate-weather-ha/assets/5826484/7bffc48f-2d2b-4cf3-973b-9d73ec745265">
