### ISSUE TITLE
API key cannot be generated

### ISSUE THREAD

**Issue by whyisthisbroken** [alexander0042/pirate-weather-ha#105]
Could not get an API Key - tryed 4 Browser and nothing happend. 
Account is activated, whether it's the Free Sub or the $25 Sub, I'm always thrown back to the main page. Pretty weird.

Am I too stupid for that or is there an error on the site?
"Login" or "Register" is always displayed at the top right, even though I'm logged in. I think the whole page is bugged.

**Comment by SamuelCarson** [comment]
Me to.

**Comment by cloneofghosts** [comment]
The steps are a bit confusing but after you've activated and finished setting up your account you have to go back to the API and click on subscribe again. After you give the subscription a name it will then show up on your subscriptions page. Clicking on the triangle under actions takes you to the subscriptions details page where you can view your API key.

![image](https://user-images.githubusercontent.com/10248058/236881361-3e1fc374-de01-4500-a911-f7a8e4033d4d.png)

**Comment by alexander0042** [comment]
Two potential issues here- one is the confusing link to see the API key, which @cloneofghosts mentioned, but the other is a weird DNS issue with the Apiable portal from time to time. 

@whyisthisbroken and @SamuelCarson, did you ever get this working?

**Comment by whyisthisbroken** [comment]
Nope - I give up this project.
Don't have time for that. I can't understand why a sign up process could be so terrible developed.... It's a mess.
Sorry for his decision.

**Comment by alexander0042** [comment]
Really sorry about this, and understand your frustration with it. I'm a data guy, so don't remotely have the skills to navigate the sign up procedures, but Apiable is definitely still working out some kinks. 

If you're still interested, shoot me an e-mail to api@alexanderrey.ca and I'll generate you a key, but understand wanting to move on.

**Comment by cloneofghosts** [comment]
@alexander0042 The signup process being confusing is good feedback to send over to Apiable for them to see if they can make things more straightforward.

**Comment by alexander0042** [comment]
Fingers crossed that's coming shortly. They're updating their portal sometime soon, so I'm hoping that this fixes it. It's a super hard issue for them to debug since it doesn't occur for them, and I can only reproduce it intermittently.

**Comment by cloneofghosts** [comment]
@alexander0042 Hopefully that helps. When I signed up to test to see if the key would generate after I verified my account I had to go back to the plans page and click subscribe on the tier I wanted to subscribe to. I was expecting after I had activated my account it would have selected the plan automatically or at least redirect me to the plans page.
