### ISSUE TITLE
wind gust sensors allways shows mph as unit

### ISSUE THREAD

**Issue by donnie-darko** [alexander0042/pirate-weather-ha#106]
Wind gust sensors allways created with the default unit of measurement (US - so mph) despite the configuration settings which is in my case SI.
Maybe this issue linked somehow with this? https://github.com/alexander0042/pirate-weather-ha/issues/96

**Comment by alexander0042** [comment]
You're spot on, and sorry for the slow update here! The new version is coming out today, which should address this

**Comment by alexander0042** [comment]
Ok, v1.2 is out, which should address this! I'm going to close the issue for now, but feel free to re-open if it crops up again or anything else comes up!

**Comment by donnie-darko** [comment]
Thanks for the new version!
Afraid it doesn't fix the issue because after the update the unit of measurement still mph
<img width="422" alt="image" src="https://github.com/alexander0042/pirate-weather-ha/assets/2626886/289f4969-734e-4e0c-9c91-f2a09d7b65de">
