### ISSUE TITLE
Error importing custom component

### ISSUE THREAD

**Issue by plangenhuizen** [alexander0042/pirate-weather-ha#107]
First of all, thanks for your work. 
I tried to use this as a drop-in replacement for DarkSky, but it returns an error after installing it via HACS and setting it up with an API key. 

I receive the following error in my log file. I am currently running Home Assistant version 2022.9.7

```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/pirateweather/sensor.py:217
Integration: Pirate Weather (documentation, issues)
First occurred: 4:36:59 PM (1 occurrences)
Last logged: 4:36:59 PM

Unexpected exception importing platform custom_components.pirateweather.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/pirateweather/sensor.py", line 217, in <module>
    device_class=SensorDeviceClass.PRECIPITATION,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: PRECIPITATION
```

Do you have any idea what I am doing wrong?

**Comment by cloneofghosts** [comment]
Are you able to update your HA installation to the latest version? The version you are currently running doesn't have the Precipitation classes which was added in HA 2022.12.

If you aren't able to update your HA install then the [legacy ](https://github.com/alexander0042/pirate-weather-ha/tree/Legacy-Dark-Sky) version is still available to use and would work in this instance.

See issues #91 and #81 for more information

**Comment by cloneofghosts** [comment]
@alexander0042 Maybe there should be text somewhere that states that the HA integration requires HA version 2022.12 or later since these sorts of issues seem to pop up occasionally. Another option would be to add it in the FAQ section on the HA page https://pirateweather.net/en/latest/ha/ or maybe add it to the description and on the HA page?

**Comment by alexander0042** [comment]
Ok, so based on [this commit](https://github.com/home-assistant/core/pull/83331) it looks like this was introduced around version 2022.10! I'm going to adjust the minimum [version for HACS](https://github.com/alexander0042/pirate-weather-ha/blob/53dcb9f0b8cafe143e16bd600de1447da19c7c8b/hacs.json#LL4C21-L4C21), and I'll a note in the docs describing this

**Comment by alexander0042** [comment]
Since we've gotten to the bottom of this and I've improved the docs, I'm going to close this issue for now. If there's anything else that comes up. please free free to either re-open or create a new issue!
