### ISSUE TITLE
Integration offline

### ISSUE THREAD

**Issue by vaemarr** [alexander0042/pirate-weather-ha#108]
Getting this error.

Retrying setup: 504, message='Gateway Timeout', url=URL('https://api.pirateweather.net/forecast/GKYRaaoHWs9w6cAkr1LmC3MV3cKmp8Ru51ouLMJo/-27.831334337290553,153.3171808719635?units=si')

**Comment by rpitera** [comment]
Same here.  Was working until an HA restart so I thought that caused it but I guess not.

Retrying setup: 500, message='Internal Server Error',

**Comment by rpitera** [comment]
@alexander0042 - No apologies necessary!  And once my finances stabilize a bit towards the end of the month I plan on making a contribution to help pay for this awesome service.  Thanks so much for your dedication.

**Comment by TiddlyWiddly** [comment]
> Is this working again? I added this integration for the first time the other day and it pulled in initial data but never updated after that.

Same issue here.

**Comment by cbird527** [comment]
> > Is this working again? I added this integration for the first time the other day and it pulled in initial data but never updated after that.
> 
> Same issue here.

I ended up figuring out my issue. Home Assistant didn't like having two weather integrations. When I disabled the old one it started working

**Comment by TiddlyWiddly** [comment]
> > > Is this working again? I added this integration for the first time the other day and it pulled in initial data but never updated after that.
> > 
> > 
> > Same issue here.
> 
> I ended up figuring out my issue. Home Assistant didn't like having two weather integrations. When I disabled the old one it started working

I have 4, this is the only one that doesn't work.

**Comment by yieldhog** [comment]
I've been running this for probably 6-9 months and upon a restart today, getting 504 gateway error as well. Doesn't come up after reload/restart.

**Comment by scstraus** [comment]
Me too.
...
Retrying setup: 504, message='Gateway Timeout', url=URL('https://api.pirateweather.net/forecast/<REDACTED>?units=si')
...

**Comment by AD-Wright** [comment]
[Looks like](https://stats.uptimerobot.com/DRKqBCok2N) it's back up and working for me now.  Had to restart HA to get it to reconnect.

**Comment by alexander0042** [comment]
This one is my fault- I broke my AWS networking, and didn't notice it quickly enough. It's all corrected now, and I've added a test to make sure it doesn't happen again. 

For future reference, there's a [status page](https://stats.uptimerobot.com/DRKqBCok2N) that checks if the endpoint is down every 5 minutes, which is useful for checking if the problem is my end or something else.
