### ISSUE TITLE
After upgrade from HA 2023.4.6 to HA 2023.5.2 Pirate Weather is offline.

### ISSUE THREAD

**Issue by mattlward** [alexander0042/pirate-weather-ha#109]
So, I finally upgraded today, will not upgrade to a .0 or .1 and the only thing that did not come back was Pirate Weather.

I am getting this in my logs:
```
Logger: homeassistant.config_entries
Source: config_entries.py:1247
First occurred: 3:42:33 PM (2 occurrences)
Last logged: 3:42:43 PM

Config entry 'Homer PW' for pirateweather integration not ready yet: 500, message='Internal Server Error', url=URL('https://api.pirateweather.net/forecast/v0pWyk8fwX67OUJIBD16N6myNugSuGcq8H0K182p/40.03729153988501,-87.96162843704224?units=si'); Retrying in background
Config entry 'Greenup PW' for pirateweather integration not ready yet: 500, message='Internal Server Error', url=URL('https://api.pirateweather.net/forecast/v0pWyk8fwX67OUJIBD16N6myNugSuGcq8H0K182p/39.2478159,-88.1633719?units=si'); Retrying in background
```

When I go to the URL in a browser I get "Endpoint request timed out".  Is the api server offline?  Or did the upgrade break Pirate Weather?

Update... I reverted to 2023.4.6 and it is not working there either.

**Comment by armdan** [comment]
same here 
`Config entry 'home' for pirateweather integration not ready yet: 500, message='Internal Server Error', url=URL('https://api.pirateweather.net/forecast/u2y8JsWzky9niOt8KEfVP8poGU7dVp717LxcyMNz/34.21469976,-118.33778124?units=si'); Retrying in background`

**Comment by SiriosDev** [comment]
same here
core-2023.5.2, Home Assistant OS

**Comment by johnwalk61** [comment]
Same issue same error same core.

Thanks

**Comment by cloneofghosts** [comment]
Looking at the [status page](https://stats.uptimerobot.com/DRKqBCok2N/784738404) it seems to be a PW rather than a HA issue. I'm not sure how much the dev looks at the github repo on the weekend so you might want to send him an email at [api@alexanderrey.ca](api@alexanderrey.ca)

**Comment by tm24fan8** [comment]
Pirate Weather is down currently. Just an unfortunate coincidence.

**Comment by mattlward** [comment]
Just dropped the author an email...

**Comment by mattlward** [comment]
Back up now...  Thanks

**Comment by SiriosDev** [comment]
are you sure? Because it still doesn't go for me (could it be that maybe the integration ran out of available calls while trying to try to connect again? )

From the new site I still can't figure out how to see the remaining calls😅

**Comment by TRusselo** [comment]
im still down
