### ISSUE TITLE
Precipitation accumulation? 

### ISSUE THREAD

**Issue by danlo315** [alexander0042/pirate-weather-ha#111]
Hi - am I doing something wrong in trying to get the precipitation accumulation sensor enabled? I have it checked in the integration setup but I'm not seeing the corresponding sensor. Thanks.

**Comment by alexander0042** [comment]
Sorry I never replied to this, and thanks to @cloneofghosts for pointing it out again. I'm going to merge these two issues together, since they're addressing the same underlying issue
