### ISSUE TITLE
Allow Extended Hourly Forecasts

### ISSUE THREAD

**Issue by sheckandar** [alexander0042/pirate-weather-ha#117]
Hello,

Thank you for the integration. It's great.

The API spec for PirateWeather allows to pull hourly reports for the next 168 hours, however, I could not find how to set that in the  HA integration settings.

It would be appreciated if that feature could be added.

**Comment by alexander0042** [comment]
That's a great point. I capped the sensors at 48 hours, since that's what Dark Sky did, but there's no reason not to request beyond that. Were you thinking about the full 168 hour range?

**Comment by sheckandar** [comment]
Yes. Pulling the whole set of available data is always the best, IMHO. The API spec seems to only allow 48 hours and 168 hours data sets. I think an option to choose between the two would be optimal.

Much appreciated.

**Comment by alexander0042** [comment]
Done and done! Sorry it took a little while to push the new version out, but v1.2.1 officially allows for sensors to be created over the full range.

**Comment by sheckandar** [comment]
> Done and done! Sorry it took a little while to push the new version out, but v1.2.1 officially allows for sensors to be created over the full range.

It is working.

Thx. Much appreciated.
