### ISSUE TITLE
Unable to connect to PirateWeather: 403 Client Error

### ISSUE THREAD

**Issue by martinrevert** [alexander0042/pirate-weather-ha#12]
I'm quite sure that my configs are ok, but it seems that PirateWeather doesn't like my api key for some reason.

Here is what I get in logs:

Logger: custom_components.pirateweather.sensor
Source: custom_components/pirateweather/sensor.py:841
Integration: pirateweather (documentation, issues)
First occurred: September 12, 2021, 7:12:51 AM (1 occurrences)
Last logged: September 12, 2021, 7:12:51 AM

Unable to connect to PirateWeather: 403 Client Error: Forbidden for url: https://api.pirateweather.net/forecast/heregoesmy hiddenapikey/-31.357253621499684,-64.22981187701225?units=si

**Comment by martinrevert** [comment]
Nevermind, sorry Alex, I was just unsubscribed from Pirateweather Beta.

**Comment by alexander0042** [comment]
Great catch- I was going to investigate this morning, but happy it's resolved!

Thanks again for using this service, and let me know if anything else crops up!
