### ISSUE TITLE
[2023.8.0b0] PirateWeather is overriding deprecated methods on an instance of WeatherEntity

### ISSUE THREAD

**Issue by dynasticorpheus** [alexander0042/pirate-weather-ha#131]
Below warning is logged as of home assistant 2023.8.0b0

`custom_components.pirateweather.weather::PirateWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.`

**Comment by frenck** [comment]
This was a beta issue and resolved in HA itself.

**Comment by dynasticorpheus** [comment]
Thanks @frenck
