### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by scarolan** [alexander0042/pirate-weather-ha#134]
Pirate weather stopped working completely today.  I tried generating a new API key and connecting but it still says "Failed Setup"

**Comment by GregoryKowalik** [comment]
Same here, the integration keeps saying in the logs: Error communicating with API: 503, message='Service Unavailable' while PirateWeather service status says everything is operational.

**Comment by akballow** [comment]
same i got API key working for a full 1 day and it broke

**Comment by GregoryKowalik** [comment]
Looks it works now. By the way still doesn't show hours on details popup when configured to show hourly forecast.

**Comment by scotttag** [comment]
Still failing for me with the same error

**Comment by mccmax1395** [comment]
I just got this error:
Config entry 'PirateWeather' for pirateweather integration not ready yet: Error communicating with API: 502, message='Bad Gateway', url=URL('https://api.pirateweather.net/forecast/F84tBaHNsibWZ3PE/42.99665547694244,-87.97736227512361?units=si&extend=hourly'); Retrying in background

Which results in the same failed to setup, will retry error

**Comment by alexander0042** [comment]
Apologies for the slow reply here. This was due to some downtime in the API, the root cause of which has finally been addressed. More importantly, I've updated the API to return a more detailed error message, which should clarify what to do in case this ever happens again (hopefully not!)
