### ISSUE TITLE
hPa decimals

### ISSUE THREAD

**Issue by TheLordVader** [alexander0042/pirate-weather-ha#14]
Thanks for your work; love it!

But how do I round the decimals for hPa using Pirateweather? When using yr.no or Swedish SMHI as provider, there are "normal" decimals...

<img width="471" alt="Screenshot 2021-09-17 at 14 45 20" src="https://user-images.githubusercontent.com/23585607/133784723-8cf2e519-66e1-4a01-a0b4-a370be0aeab9.png">

**Comment by alexander0042** [comment]
Thanks for pointing this out (and using this service)! I thought I'd fixed this bug, but apparently not! Let me dig into it and see if I can't tease this one out for good.

**Comment by alexander0042** [comment]
Got it! Turns out that I fixed it (nothing fancy, just a python `round()` ) for currently and hourly conditions, but forgot about daily. It's updating now, so should work its way through the cache in about half an hour or so

**Comment by TheLordVader** [comment]
Thank you for a fast reply! Great, dig when you have the time, and thanks for your effort!

**Comment by giustanca** [comment]
Hi, same problem here. There is a solution?

**Comment by alexander0042** [comment]
That's weird- I thought I fixed this one, but clearly not! 
What unit system are you using?

**Comment by giustanca** [comment]
The unit system is metric
![Screenshot_20211002-203138](https://user-images.githubusercontent.com/58627621/135728078-819a6147-5a71-4df4-8ec6-e5c5276c479b.jpg)

**Comment by alexander0042** [comment]
Ok, fixed this one for real this time! The values were rounded, but when they were multiplied by the units for the pressure, Python would sometimes have issues with the floating points, leading to this issue. 
I added another rounding statement at the output step, so should be good to go here!

Sorry about this, and thanks again for bringing it to my attention

**Comment by risozhor** [comment]
FYI: I'm just edited one line in "/config/custom_components/pirateweather/weather.py" file, and it works for me
![2021-10-04_150752](https://user-images.githubusercontent.com/12980782/135848870-bc033398-50e4-4d1a-9189-171089a0c98c.png)

**Comment by alexander0042** [comment]
Great point! It should be fixed on the back end with the last API update, but I like this solution too, since this integration does its own processing. Just pushed this commit: <https://github.com/alexander0042/pirate-weather-ha/commit/2ead9649ec2439d8b6825bf1a25ede004e8063e5>

**Comment by giustanca** [comment]
Problem solved. Thank you very much!
