### ISSUE TITLE
Home Assistant error: "The pirateweather integration is using deprecated forecast"

### ISSUE THREAD

**Issue by mikesellt** [alexander0042/pirate-weather-ha#140]
I'm seeing a notification in my Home Assistant reporting "The pirateweather integration is using deprecated forecast."  It also says "This stops working in version 2024.3.0. Please address before upgrading."  I just wanted to open this since I hadnt' seen the request opened yet. Thanks for all your work on this project.  I've enjoyed using it.

**Comment by AD-Wright** [comment]
This is being tracked in #136.

**Comment by alexander0042** [comment]
Thanks for posting this- it is in progress, and so I'm going to close this issue to keep things tidy! You should get an auto-update whenever the new version comes out, so should be fixed then
