### ISSUE TITLE
All temperatures are +100

### ISSUE THREAD

**Issue by mermelmadness** [alexander0042/pirate-weather-ha#141]
Well, this was interesting to see this afternoon.
![image](https://github.com/alexander0042/pirate-weather-ha/assets/38080873/f5ec3da9-936d-41b8-b690-df4263299df9)
Normally I wouldn't care, but I do have some automations that go off the reported outside temperature.

I'm guessing this has nothing to do with your integration but the reporting from Pirate Weather itself, just thought I'd share anyway.

**Comment by cloneofghosts** [comment]
This is an API issue where everything is defaulting to us units no matter which one you have selected. Seems to have started this afternoon and you can follow along here https://github.com/alexander0042/pirateweather/issues/99

**Comment by mermelmadness** [comment]
I figured.  Thanks for pointing me to the correct issue number.  I subscribed to stay informed.  Kinda laughed when I saw it.
