### ISSUE TITLE
wrong value at weather.pirateweather.net?

### ISSUE THREAD

**Issue by risozhor** [alexander0042/pirate-weather-ha#18]
Hi. Many thanks for Your great work!
I don't know its that right, but I think its wrong value 'Cloud coverage' at https://weather.pirateweather.net/

![image](https://raw.githubusercontent.com/risozhor/risozhor/main/2021-09-29_183151.png)

**Comment by alexander0042** [comment]
Thanks for reaching out, I always love to hear from people that are using the service! 

Appreciate you catching that- although maybe it’s just very, very, very cloudy, it’s probably an issue with the interpolation. I use a cubic interpolation between data points, which means that if it’s a weird set of input values, it can sometimes produce this result. I’ve already set it up to avoid negative values, but didn’t think about high ones!

I’ll push an update in the next couple days to fix this. Thanks again for pointing it out ☁️ 

Alexander

**Comment by alexander0042** [comment]
Ok, done and done! I've added a new cap to the cloud cover response which should make sure this doesn't show up again.

Let me know if you notice anything else, and thanks again for using this service!

Alexander

**Comment by risozhor** [comment]
`Let me know if you notice anything else, and thanks again for using this service!`
Ok, and many thanks for You again!
