### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirate-weather-ha#21]
The last two nights at my location it got foggy overnight but when I checked the website it showed a visibility value of 0.1km but it did not show the fog icon.

As far as I am aware a visibility under 1km is considered fog though it might need to be over 75% humidity like Mist needs to be otherwise it would be considered Haze/Smoke/etc.

If you need an example here is Thunder Bay, Ontario where it has a visibility of 0.1km. The two blank icons on the weather page are the fog icons (that also needs to be fixed) and checking the api it seems that it shows when the visibility is exactly 0.
![image](https://user-images.githubusercontent.com/10248058/136400755-197e4d37-64aa-497d-8dc7-7280950a522c.png)

**Comment by alexander0042** [comment]
Hi,

Thanks for pointing this out! That definitely is an issue- I think the API is returning the fog icon (although I need to double check how it's calculated), and the website is missing that icon for some reason. Let me dig into this one and get back to you!

Thanks,
Alexander

**Comment by alexander0042** [comment]
Haven't forgotten about this! I think I've addressed the main issue here- the fog icon from that set has been added in, and updated the weather-vue [code to use it](https://github.com/alexander0042/weather-vue/commit/1a6562ac04e18731f9494b8e28c2c0be20c51284)! Unfortunately, there doesn't seem to be fog anywhere, so I can't test this out, but I'll keep an eye out for some fog somewhere to test it.

I really like the idea of adding a wind icon in, and I think the best way to go about it is adding a different unit. Something along the lines of "si-wind" or "us-wind", which would return it as a icon. This would preserve compatibility with Dark Sky, but provide it as an option?

**Comment by cloneofghosts** [comment]
They were forecasting fog patches last night but I didn't check to see if it was fixed or not. Whenever I find a location to check I will definitely check for you.

I don't know what the parameters for the wind icon to show on DarkSky are since it isn't mentioned anywhere in their docs but it might be 40 km/h, 25 mph, 11 m/s? All those convert to roughly the same speed in the different unit types so maybe that could be used for the icon?

**Comment by cloneofghosts** [comment]
Just following up on this. I'm seeing visibility of 0.2km and cloudy. Looking at the hourly forecast I don't see any fog so I cannot confirm if it works on the website.

**Comment by cloneofghosts** [comment]
I just noticed that in the hourly forecast it shows the sleet icon with a summary of None or Snow sometimes in the API. I haven't seen any other instances of this in the API so I'm not sure why it's happening now.

```
"time": 1640440800,
"icon": "sleet",
"summary": "None",
```

```
"time": 1640444400,
"icon": "sleet",
"summary": "Snow",
```
