### ISSUE TITLE
cloud coverage  133%

### ISSUE THREAD

**Issue by loki-sft** [alexander0042/pirate-weather-ha#23]
Pirate weather is giving me a cloud coverage greater than 100%.
https://weather.pirateweather.net/ is showing the same value 133%
Dark Sky shows cloudy.pnp as icon.

If I look outside, the sky is sunny blue.

**Comment by alexander0042** [comment]
Hi,

Thanks for the report! I’d thought for sure I’d fixed this one, so good to know that I didn’t. Do you mind letting me know roughly where this occurred (either here or via email to api@alexanderrey.ca), so I can see what model is feeding into the API here? 🌥

**Comment by loki-sft** [comment]
This is roughly where I live:
Braunschweig, Deutschland

**Comment by alexander0042** [comment]
Great, thanks! I’ll take a look at the logs tomorrow and see what I can figure out!

**Comment by alexander0042** [comment]
Ok, I know I said I fixed this before, but not it's fixed for real (hopefully)! Issue this time was that my max() function was set to stop everything above 100; however, the API returns a value from 0 to 1, so 100 wasn't a very useful max!

Thanks again for your comment (and patience) here! Feel free to re-open this if it crops up again, or start a new issue if anything else comes up
