### ISSUE TITLE
https://api.pirateweather.net is down?

### ISSUE THREAD

**Issue by Hukuma1** [alexander0042/pirate-weather-ha#31]
Not really an issue here per say, wondering if this is some AWS outage? 

I'm located in the US.

<img width="1027" alt="isitdown" src="https://user-images.githubusercontent.com/54511555/146879065-31419768-2c15-4bc0-92c1-8f8237991032.png">

**Comment by NCC1941** [comment]
Same issue here.

According to my HA logs, Pirate Weather was down for almost 6 hours coinciding withHukuma1's report, then came back online.
However, it is now down again, having gone down about 3 hours ago.

**Comment by Hukuma1** [comment]
Came back here for this. Down for me again as well. :/

**Comment by alexander0042** [comment]
Bah humbug! Thanks for the reports here- logged in and fixed it, so we're back online now ☀
