### ISSUE TITLE
Bad Gateway Errors in North American Cities

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirate-weather-ha#33]
Seems like something is broken with the API as it started giving 502 errors and visiting api.pirateweather.net just returns the Internal service error message. Visiting weather.pirateweather.net it just spins endlessly.

It seems to only be an issue with locations in North America as when I try with cities from other countries everything works correctly.

**Comment by alexander0042** [comment]
That's kind of weird- things seem to be up and working for me? Is there a specific city you're looking at?

I'm putting in some major updates this week, so not impossible that there will be some issues, but shouldn't be any problems at this point

**Comment by cloneofghosts** [comment]
It seems to have fixed itself. My guess is that there was something wrong with the model used in North America and the next update it fixed itself.

**Comment by cloneofghosts** [comment]
I'm going to close this issue for now as it seems that the errors have cleared up. If it happens again I'll reopen the issue.

**Comment by martinhoess** [comment]
Seems as if there is still a problem. Can also be reproduced with the weather page
https://pirateweather-api.herokuapp.com/weather/v1/json?lat=34.0522342&lon=-118.2436849&units=ca
results in a 502 bad gateway

![image](https://user-images.githubusercontent.com/47973549/147665940-7c14e59f-fc75-4442-9b1e-6f55f28d3218.png)

Home Assistant also gets 502
![image](https://user-images.githubusercontent.com/47973549/147666031-9d63e5ae-7516-4408-a1e4-2cca9a0b62f1.png)

**Comment by cloneofghosts** [comment]
@martinhoess There was a different issue pointed out in #34 which is now fixed.

If there are any errors with the service and there are no active issues you should ideally open a new issue. I'm not sure what notifications that alexander gets but the best chance of getting something noticed and fixed is to create a new issue.
