### ISSUE TITLE
Pirate-Weather is down

### ISSUE THREAD

**Issue by myopenflixr** [alexander0042/pirate-weather-ha#34]
Hello,

Pirate-weather appears to be down. I noticed it this morning within Home Assistant.

I also checked [https://weather.pirateweather.net/](https://weather.pirateweather.net/) and it is down as well.

**Comment by alexander0042** [comment]
Sorry- was trying to improve something, broke it instead! Luckily, AWS Lambda is versioned, so rolling back now, should be back up in 10

**Comment by alexander0042** [comment]
Thanks for understanding! I'm super close to being able to solve a ton of these downtime issues by keeping previous model results online for a week, so hopefully soon this will be way less of a problem

**Comment by alexander0042** [comment]
With the V1.0 release of this API, the underlying cause of this issue should be resolved, so I'm going to go ahead and close this for now. 

Thanks again for using this service, and let me know if anything else comes up!
