### ISSUE TITLE
[IDEA] Humidity forecast

### ISSUE THREAD

**Issue by max5962** [alexander0042/pirate-weather-ha#37]
Hello,

Any way to get the humidity forcast ? 
i'd like to create freeze alert so i need the temperature and humidity forcast 
Thanks

**Comment by alexander0042** [comment]
Hi- thanks for using this service and reaching out! 

Good news here! Humidity is already included in the forecast, so the data's there. If you use the "sensor" module, you can request the humidity forecast, and then integrate it however you'd like

**Comment by max5962** [comment]
indeed ! 
Awesome project ! 
Thnaks
