### ISSUE TITLE
Unable to connect to PirateWeather - CertificateError

### ISSUE THREAD

**Issue by xstrex** [alexander0042/pirate-weather-ha#47]
When HA starts, I'm getting the following error: 
`2022-05-27 19:27:28 ERROR (SyncWorker_3) [custom_components.pirateweather.weather] Unable to connect to PirateWeather. HTTPSConnectionPool(host='api.pirateweather.net', port=443): Max retries exceeded with url: /forecast/om3xxPNoEt94XXXXXXXXXXCM78xtHiJ2s5iZsYa/XX.XXX50780789178,-XXX.XXX9254007341?units=us (Caused by SSLError(CertificateError("hostname 'api.pirateweather.net' doesn't match either of 'susi.comcast.net', '*.aws-np.susi.comcast.net', '*.aws-np.susi.xfinity.com', '*.aws.susi.comcast.net', '*.aws.susi.xfinity.com', '*.susi.comcast.net', '*.susi.xfinity.com', 'register-dev.xfinity.com', 'register-ng.xfinity.com', 'register-qa.xfinity.com', 'register-st.be.xfinity.com', 'register-st.xfinity.com', 'register-wg-st.bi.xfinity.com', 'register-wg-st.xfinity.com', 'register-wg.bi.xfinity.com', 'register-wg.xfinity.com', 'register.be.xfinity.com', 'register.xfinity.com'")))`

Yet when I visit the URL directly I get valid JSON:
https://api.pirateweather.net/forecast/om3xXXXXXXXXXXXXXXXXXn3fCM78xtHiJ2s5iZsYa/XX.XX450780789178,-XXX.XXX29254007341?units=us

(sensitive info redacted) 

Running: e95083f
HA: 2022.5.5
In Docker; official container

I'm not understanding why it's trying to compare api.pirateweather.net with a .xfinity.* cert.

**Comment by milandzuris** [comment]
same

**Comment by alexander0042** [comment]
Ok, so more people impacted by the same thing typically helps with troubleshooting! Did you happen to test out either of the ideas I commented above?

**Comment by xstrex** [comment]
Thanks for digging into this, I know it's a weird one. 

I haven't had time to troubleshoot further, I'll get it done in a day or so. 

The Wi-Fi/Ethernet I don't think is applicable here. HA exists in a docker container, on a NAS, connected via bonded Ethernet to a managed switch, then to a router & modem. So, the docker container is getting the error, not any of the clients, wired, or wireless. 

I'll try the http/https option tomorrow, and report back. 

Cheers.

**Comment by alexander0042** [comment]
Thanks! One other idea might be to try setting a manual DNS on the docker container (ex. 1.1.1.1), although based on the complexity of the setup you described there you might already be doing that!

**Comment by xstrex** [comment]
Ok, this is interesting.. 

I just got roughly the same error for another custom component, unrelated to yours. 

```
Logger: homeassistant.setup
Source: components/digital_ocean/__init__.py:51 
First occurred: 8:12:18 PM (1 occurrences) 
Last logged: 8:12:18 PM

Error during setup of component digital_ocean
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname 'api.digitalocean.com' doesn't match either of 'susi.comcast.net', '*.aws-np.susi.comcast.net', '*.aws-np.susi.xfinity.com', '*.aws.susi.comcast.net', '*.aws.susi.xfinity.com', '*.susi.comcast.net', '*.susi.xfinity.com', 'register-dev.xfinity.com', 'register-ng.xfinity.com', 'register-qa.xfinity.com', 'register-st.be.xfinity.com', 'register-st.xfinity.com', 'register-wg-st.bi.xfinity.com', 'register-wg-st.xfinity.com', 'register-wg.bi.xfinity.com', 'register-wg.xfinity.com', 'register.be.xfinity.com', 'register.xfinity.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.digitalocean.com', port=443): Max retries exceeded with url: /v2/account/?per_page=200 (Caused by SSLError(CertificateError("hostname 'api.digitalocean.com' doesn't match either of 'susi.comcast.net', '*.aws-np.susi.comcast.net', '*.aws-np.susi.xfinity.com', '*.aws.susi.comcast.net', '*.aws.susi.xfinity.com', '*.susi.comcast.net', '*.susi.xfinity.com', 'register-dev.xfinity.com', 'register-ng.xfinity.com', 'register-qa.xfinity.com', 'register-st.be.xfinity.com', 'register-st.xfinity.com', 'register-wg-st.bi.xfinity.com', 'register-wg-st.xfinity.com', 'register-wg.bi.xfinity.com', 'register-wg.xfinity.com', 'register.be.xfinity.com', 'register.xfinity.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/digital_ocean/__init__.py", line 51, in setup
    if not digital.manager.get_account():
  File "/usr/local/lib/python3.9/site-packages/digitalocean/Manager.py", line 34, in get_account
    return Account.get_object(api_token=self.token)
  File "/usr/local/lib/python3.9/site-packages/digitalocean/Account.py", line 23, in get_object
    acct.load()
  File "/usr/local/lib/python3.9/site-packages/digitalocean/Account.py", line 28, in load
    data = self.get_data("account/")
  File "/usr/local/lib/python3.9/site-packages/digitalocean/baseapi.py", line 164, in get_data
    req = self.__perform_request(url, type, params)
  File "/usr/local/lib/python3.9/site-packages/digitalocean/baseapi.py", line 98, in __perform_request
    return requests_method(url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.digitalocean.com', port=443): Max retries exceeded with url: /v2/account/?per_page=200 (Caused by SSLError(CertificateError("hostname 'api.digitalocean.com' doesn't match either of 'susi.comcast.net', '*.aws-np.susi.comcast.net', '*.aws-np.susi.xfinity.com', '*.aws.susi.comcast.net', '*.aws.susi.xfinity.com', '*.susi.comcast.net', '*.susi.xfinity.com', 'register-dev.xfinity.com', 'register-ng.xfinity.com', 'register-qa.xfinity.com', 'register-st.be.xfinity.com', 'register-st.xfinity.com', 'register-wg-st.bi.xfinity.com', 'register-wg-st.xfinity.com', 'register-wg.bi.xfinity.com', 'register-wg.xfinity.com', 'register.be.xfinity.com', 'register.xfinity.com'")))
```

**Comment by xstrex** [comment]
So this is a weird one, but it seems to have been an issue with Comcast/Xfinity. I don't make any configuration change, and it just started working a few days ago. 

For anyone else who finds this..
My "deal" expired with xfinity (though I still had service), once I got a new "deal" with a better price, the issue seems to of resolved itself, or so it appears. May be completely unrelated, but seems like an odd coincidence. 

Component is working great again!

**Comment by alexander0042** [comment]
Thank you so much for posting the update here! I can't say enough how much I appreciate it when I'm looking for a solution and someone posted the fix that works for them in the thread, so this is idea (even if it's still a bit of a mystery).

I'm hoping that it was a fix Comcast rolled out, but either way, good that it's resolved. If you run into any other issues or have another idea, feel free to open a new issue and we can go from there!

Thanks,
Alexander
