### ISSUE TITLE
weather quite wrong for Oxfordshire, UK

### ISSUE THREAD

**Issue by JCHH2** [alexander0042/pirate-weather-ha#48]
Hi,

I'm not quite sure what's happening, but Pirate weather is showing it to be sunny right now, but there's 100% cloud cover.

This screenshot shows HA's weather card, yours and the the UK Met office card.

![Screenshot 2022-06-01 at 11 21 43](https://user-images.githubusercontent.com/34644672/171383058-318f9728-1405-4276-9fb3-b77a25257f6f.png)

I don't have access to Dark Sky's API, but I do use their website which shows:
![Screenshot 2022-06-01 at 11 23 12](https://user-images.githubusercontent.com/34644672/171383300-3516fa03-b880-453c-a532-8dd98fc41109.png)

I am happy to help troubleshoot :-)

**Comment by alexander0042** [comment]
Hi- I'm really sorry I missed this. I was camping and it got lost in the deluge of messages when I got back. Now that I've flagged it I'll be faster as responding here. These summer storms are really tricky to get right. They tend to come up pretty suddenly and have very light rain, which is something the models seem to struggle with. 

If you can remember, was it raining when this occurred? And do you know if it cleared up at all later in the day?

Let me know if (when) this occurs again and I'll see if I can check the underlying model results to try to tease this out.

Thanks,
Alexander

**Comment by jchhenderson** [comment]
Hi, thanks!

No, it wasn't raining.
Yes, it got clear up later in the day.

> Let me know if (when) this occurs again

...will do - cheers.
