### ISSUE TITLE
Precipitation for the hour graph 

### ISSUE THREAD

**Issue by mjm8975** [alexander0042/pirate-weather-ha#49]
First of all thanks for your work on this!

Is there a way to get the precipitation for the hour graph below as seen on weather.pirate weather.net in home assistant
![7AA9395A-17B5-474B-A0A6-8C53B9A2C0AA](https://user-images.githubusercontent.com/13999054/173559305-dd4b1318-af96-47f2-a6e2-5d16b3b2a203.jpeg)

**Comment by cloneofghosts** [comment]
I was looking to do something similar to this a while ago and I came to the conclusion that it isn't possible. While there are integrations in HA to display a graph like the image but I didn't see a way to access the minutely data in the integration. The dev would need to add the ability to get minutely data for it to be possible.
