### ISSUE TITLE
All secondary entities unavailable

### ISSUE THREAD

**Issue by mermelmadness** [alexander0042/pirate-weather-ha#51]
Randomly yesterday, all entities other than the normal weather card become unknown.  Did something happen?  Did I miss anything?  My account should still have over 9000 API calls for this month, so I know I'm not over.
![image](https://user-images.githubusercontent.com/38080873/175172065-a96ae422-5836-4c8d-b8b6-ca53a2d362cb.png)

**Comment by mermelmadness** [comment]
Nevermind, I just needed to redownload it from HACS.

**Comment by alexander0042** [comment]
Hi,

Thanks for replying to explain what worked for you here! That's kind of a weird glitch, but happy that it's solved. 
Let me know if anything else crops up or if you have any other ideas/ comments/ suggestions
