### ISSUE TITLE
Warning: Overriding Deprecated Methods

### ISSUE THREAD

**Issue by AlexKusnezov** [alexander0042/pirate-weather-ha#52]
```
custom_components.pirateweather.weather::DarkSkyWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.
```

**Comment by conrad66** [comment]
I would not like to wait for January 2023....

**Comment by alexander0042** [comment]
Totally get that! Just to confirm, is the integration still working but throwing a warning, or does this disable the integration?

**Comment by ChaseCares** [comment]
The integration continues to work fine, just throws this warning on start up.

**Comment by alexander0042** [comment]
Fix for this (and several other issues) has is ready for testing! If you have a minute I'd love it if you could help test it out. The instructions are here: <https://github.com/alexander0042/pirate-weather-ha/issues/57>

**Comment by alexander0042** [comment]
And we're live! I pushed this update out via HACS today, so I'm going to close this thread for now. Thanks again for reporting this issue and using this API, and please don't hesitate to open a new issue if anything else comes up.
