### ISSUE TITLE
Deprecated Utility: convert_pressure

### ISSUE THREAD

**Issue by coaster3000** [alexander0042/pirate-weather-ha#55]
> Logger: homeassistant.helpers.frame
> Source: helpers/frame.py:77
> 
> First occurred: October 9, 2022 at 7:26:06 PM (1 occurrences)
> Last logged: October 9, 2022 at 7:26:06 PM
> 
> Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for pirateweather using this method at [custom_components/pirateweather/weather.py, line 169](https://github.com/alexander0042/pirate-weather-ha/blob/e95083f235817ba3f5653114afe5602ab323b8ae/custom_components/pirateweather/weather.py#L169): return round(convert_pressure(pressure, PRESSURE_HPA, PRESSURE_INHG), 2)

I believe there is a typo in the warning message because of the version numbers mentioned have already passed. As for the low occurance count, I had a recent log clear.

https://github.com/alexander0042/pirate-weather-ha/blob/e95083f235817ba3f5653114afe5602ab323b8ae/custom_components/pirateweather/weather.py#L169

**Comment by coaster3000** [comment]
A patch has corrected the deprecation dates and is affective the year 2023

**Comment by alexander0042** [comment]
Hi,

Thanks for pointing this out! I've incorporated this update into the broader config-flow version of this integration, and if you have a minute I'd love it if you could help test it out. The instructions are here: <https://github.com/alexander0042/pirate-weather-ha/issues/57>

**Comment by coaster3000** [comment]
Sure thing, I would love to assist any way I can. I am not very active though due to my work and college schedule, but I would be happy to assist in spare time.

**Comment by alexander0042** [comment]
I pushed the updated version that addressed this (and many other things) to HACS today, so going to close this issue for now. Let me know if anything else comes up, and thanks again for opening this issue and using this integration!
