### ISSUE TITLE
Deprecation Warning: overriding deprecated methods on an instance of WeatherEntity

### ISSUE THREAD

**Issue by pcanham** [alexander0042/pirate-weather-ha#56]
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:308
Integration: Weather ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: 08:58:39 (1 occurrences)
Last logged: 08:58:39

custom_components.pirateweather.weather::DarkSkyWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

**Comment by pcanham** [comment]
Closing due to duplicate should have checked the other tickets first

#52

**Comment by alexander0042** [comment]
Hi,

Thanks for opening (and closing) this issue! The code rewrite to fix this is 95% done and will be released soon, so should have a solution shortly. If you’d like to take a look, check out the “dev config flow” branch, which is where I’m working on things. 

Let me know if you encounter any other issues here, and thanks for using this integration!
