### ISSUE TITLE
Distance never shows

### ISSUE THREAD

**Issue by Spankythemusical** [alexander0042/pirate-weather-ha#59]
While I love the PirateWeather sensors, it has never showed a value for nearest_storm_distance.  Even with rain outside it still shows as 0.  Is this a sensor that simply no longer exists, or is there a configuration that I am missing?

**configuration.yaml**

`weather:
  - platform: darksky
    api_key: !secret darksky_api
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_longitude
    mode: "hourly"
`
**sensor.yaml**

`
- platform: darksky
  api_key: !secret darksky_api
  scan_interval: '00:15:00'
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  monitored_conditions:
    - alerts
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - cloud_cover
    - daily_summary
    - dew_point
    - hourly_summary
    - humidity
    - icon
    - minutely_summary
    - moon_phase
    - nearest_storm_bearing
    - nearest_storm_distance
    - ozone
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_type
    - pressure
    - summary
    - sunrise_time
    - sunset_time
    - temperaturee
    - temperature_high
    - temperature_low
    - uv_index
    - visibility
    - wind_bearing
    - wind_gust
    - wind_speed
`

**Comment by cloneofghosts** [comment]
This issue was brought up in a separate [repository](https://github.com/alexander0042/pirateweather/issues/6) and the answer from the developer is that particular parameter doesn't actually work currently. The developer gave some ideas on how he could implement but he has gotten busy and hasn't had a chance to implement anything for this.

I believe that these parameters are the only ones which do not work currently:
* nearestStormDistance
* nearestStormBearing
* nearest-station (PW doesn't actually use any station data currently)

**Comment by Spankythemusical** [comment]
Thank you very much for this!  I didn’t realize there was another repository.  I’ll watch that one for any future updates.  Thanks again!

**Comment by cloneofghosts** [comment]
You're welcome! That other repository is for the main PW website and is for general API issues not related to HA.

It could also be that the dev was going to look into it and then just forgot about it and this issue and/or commenting on that other one will serve as a reminder to look into it after the new HA flow is complete.

**Comment by alexander0042** [comment]
Thanks @cloneofghosts for responding to this! Your answer here is exactly correct, they're not working at the moment, but are on the list of things to improve at some point. 

Thanks again for using this API, and let me know if you notice any other issues or have an idea!
