### ISSUE TITLE
When adding custom repository for pirate weather, HA does not recognize the repo

### ISSUE THREAD

**Issue by alexuadler** [alexander0042/pirate-weather-ha#68]
When I add the repository listed in the installation instructions in the readme, I get the following error:

`https://github.com/alexander0042/pirate-weather-ha is not a valid add-on repository`

My version list:
Home Assistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest

**Comment by alexander0042** [comment]
That's an unusual error. If you're using HACS, Pirate Weather should show up in the default list, so adding a new repository shouldn't be required here

**Comment by alexuadler** [comment]
Ah, this is user error. I was attempting to add the repository in the normal addons location, not via integrations in HACS. Thank you for responding!
