### ISSUE TITLE
How to show in dashboard ?

### ISSUE THREAD

**Issue by tevas007** [alexander0042/pirate-weather-ha#70]
Hello,

i have installed Pirate Weather integration, but how to show or add pirate weather to the dashbord ?

**Comment by alexander0042** [comment]
Thanks for trying out this integration and apologies for the problems! Once you install via HACS, you need to go to the integrations UI on Home Assistant, click the add button, search for "Pirate Weather", and go from there!

**Comment by tevas007** [comment]
Hello,

Thank you. I am doing exactly as you are saying:
[image: image.png]

But what next ? I do not see Pirate Weather on the dashboard. How to
add/open it?

**Comment by alexander0042** [comment]
For whatever reason, that image isn't showing on my end, can you try posting it again? Also, anything showing up in your logs?

**Comment by tevas007** [comment]
![image](https://user-images.githubusercontent.com/109091323/210384283-0e5edf1b-79b8-4469-987b-b96e21977938.png)

**Comment by tevas007** [comment]
![image](https://user-images.githubusercontent.com/109091323/210384413-0645d07e-5774-4dd9-9751-afb46cdc42b9.png)

**Comment by tevas007** [comment]
Logger: homeassistant.components.weather
Source: custom_components/pirateweather/weather.py:219
Integration: Weather (documentation, issues)
First occurred: 09:12:49 (1 occurrences)
Last logged: 09:12:49

Error while setting up pirateweather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/pirateweather/weather.py", line 181, in async_setup_entry
    pw_weather = PirateWeather(name, unique_id, forecast_mode, weather_coordinator, outputRound)
  File "/config/custom_components/pirateweather/weather.py", line 219, in __init__
    self._ds_currently = self._weather_coordinator.data.currently()
AttributeError: 'NoneType' object has no attribute 'currently'

**Comment by tevas007** [comment]
This error originated from a custom integration.

Logger: custom_components.pirateweather.weather_update_coordinator
Source: helpers/update_coordinator.py:201
Integration: Pirate Weather (documentation, issues)
First occurred: 09:12:49 (1 occurrences)
Last logged: 09:12:49

Error requesting pirateweather data: 403, message='Forbidden', url=URL('https://api.pirateweather.net/forecast/rPKX3Tfuuy8jp7X2nzMN87UK5sqBGw5V1h9dB8Q8/54.6781,25.2979?units=si')

**Comment by alexander0042** [comment]
Thank you for sharing all that! The last message is the key one here- you need to log into the API dashboard and click subscribe on the beta forecast API page: <https://pirateweather.net/apis/hv9nrw1tjg/Beta>. This is a good note that I should improve the logs to clarify this step though, since it's super easy to miss!

**Comment by tevas007** [comment]
ok. I ahve subscribed:
![image](https://user-images.githubusercontent.com/109091323/210419703-9d029b82-5dc0-4741-8e3d-7be932b2440c.png)

**Comment by tevas007** [comment]
Closed it in integrations:
![image](https://user-images.githubusercontent.com/109091323/210419913-ac056251-41b3-4711-a74d-4f234849dece.png)

**Comment by tevas007** [comment]
But what to do next ? How to display it in dashboard?

**Comment by alexander0042** [comment]
Hmm, now that you're subscribed it makes this issue stranger! Is there anything else showing up in the logs, since otherwise the weather entity should just "show up"?

**Comment by tevas007** [comment]
ok, now i see entities. Maybe restart was needed. But how to group all entities into one card ? Not by going and selecting one by one?
![image](https://user-images.githubusercontent.com/109091323/210959255-6e674d02-d0d6-4cff-99f4-c5cb657df257.png)

**Comment by alexander0042** [comment]
Ok, we're close here! The last step to get this in the dashboard is to select "weather" instead of sensor during the setup. This will create the standard HA weather card, which is probably what you're looking for

**Comment by tevas007** [comment]
yes, when selecting "weather" everything is fine. But I want to display all available sensors (which is more than 200) information in one card.

**Comment by alexander0042** [comment]
Now that's a trickier question. There are a few Home Assistant cards for integrating weather data, so might be worth checking out one of those, or assigning them all to a "Weather" area and grouping them that way. 

Since I think we've sorted out all the Pirate Weather issues here, I'm going to go ahead and close this issue for now; however, feel free to re-open this or create a new issue if anything else comes up!
