### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [alexander0042/pirate-weather-ha#71]
This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

**Comment by alexander0042** [comment]
Thank you so much for alerting me to this! I've been basing most of this integration off the HA's Dark Sky sensor, but a few legacy things have slipped through here and there. 

I've pushed a new version to HACS that should fix this, so hopefully is resolved with that! I'm hoping to eventually submit this to be included with HA core, so I'm going to keep working on modernizing the code and bringing it up to the current HA standards over time.

**Comment by frenck** [comment]
No problem! Looking forward to see new things like this being added to the Core ❤️ 

../Frenck
