### ISSUE TITLE
sensor.pirateweather_temperature is using native unit of measurement

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [alexander0042/pirate-weather-ha#72]
After Update to HA 2023.1 I get following warning  în logs

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:980
Integration: Sensor (documentation, issues)
First occurred: 00:00:45 (2 occurrences)
Last logged: 00:00:45

Entity sensor.pirateweather_temperature (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.pirateweather_humidity (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by alexander0042** [comment]
Hi, thanks for opening this issue! I've corrected this in the latest version (1.02), so this error should be resolved as soon as you update.
