### ISSUE TITLE
Pressure sensor is missing state_class

### ISSUE THREAD

**Issue by p6sfrx725z28knfy** [alexander0042/pirate-weather-ha#73]
Seems the values of the PirateWeather Pressure sensor cannot be graphed as it lacks the "state_class: measurement" present on the temperature and humidity sensors:

PirateWeather Hourly Pressure:
```
attribution: Powered by Pirate Weather
unit_of_measurement: mbar
device_class: pressure
friendly_name: PirateWeather Hourly Pressure

```
Vs

PirateWeather Hourly Temperature:
```

state_class: measurement 
attribution: Powered by Pirate Weather
unit_of_measurement: °C 
device_class: temperature 
friendly_name: PirateWeather Hourly Temperature

```

**Comment by alexander0042** [comment]
Hi, 

Thanks for pointing that out, it's a really good observation. I based this chunk of the integration off the built in Dark Sky one (<https://github.com/home-assistant/core/blob/9d45071e3fe0cda4c21a5208f0db4104bffffaa5/homeassistant/components/darksky/sensor.py#L267>, which doesn't give a state class for the pressure sensor. I can't image why it would be a problem though, so I'll try adding it in and see if anything changes

**Comment by p6sfrx725z28knfy** [comment]
Thankfully I have come across the lack of state_class before so was able to add this locally using customize.yaml and confirmed this now displays as expected in the Statistics Graph card :)

```
  customize:
    sensor.pirateweather_hourly_pressure:
      state_class: measurement

```

**Comment by alexander0042** [comment]
This is a great workaround, so thank you for posting it! The permanent fix will come out in the next integration release, so I'll leave this issue open for reference until then

**Comment by alexander0042** [comment]
And we're live (v1.1.0) is live! I'm going to close this for now, but feel free to either re-open or start a new issue if this, or anything else, crops up again
