### ISSUE TITLE
How to Remove Hourly Forecast Sensors

### ISSUE THREAD

**Issue by cloneofghosts** [alexander0042/pirate-weather-ha#79]
I'm a bit of a HA noob but I cannot for the life of me figure out how to remove the hourly sensors without removing the whole integration and setting it up again. Once there is a value in the hourly sensors box there is no way to remove the value and HA says that PW is still providing the sensors so I cannot remove them. Is it because I have daily sensors setup for the same conditions so it doesn't let me remove them?

Here's a screenshot of the options page if that helps:
![image](https://user-images.githubusercontent.com/10248058/212720366-2b0dce02-4af7-42c5-ab02-517d55fa0341.png)

I also see no option to change the API key and the update rate on the options page without removing the integration also.

**Comment by cloneofghosts** [comment]
@alexander0042 I still haven't been able to figure this one out. The only way I can think of to fix this issue is to remove the integration and then remove all the leftover sensors and re-add it which is less than ideal.

**Comment by cloneofghosts** [comment]
If the update interval and key aren't editable from the options menu that's fine was curious if it was something that you could add. Maybe the documentation site needs a page dedicated for Home Assistant stuff?

**Comment by alexander0042** [comment]
A HA specific docs page is a great idea, I'll see what I can pull together. In the meantime, I've worked out a solution to this. It's not super elegant, but I'll set it in the next version that if you type in "None", then it'll mark the unused ones for removal, and then they can be manually deleted!

I'm just going through the issues list to see if there's anything else I need to address, but otherwise I'll push this later tonight or tomorrow

**Comment by cloneofghosts** [comment]
I solution doesn't need to be elegant as long as it works but it's nice that you found a solution. I'll keep this open until the new release is out.

**Comment by alexander0042** [comment]
Ok, and we're live! I added some text to explain that "None" needs to be typed in the options flow, so let me know how it goes

**Comment by cloneofghosts** [comment]
Was able to get them removed. Thanks.
