### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [alexander0042/pirate-weather-ha#82]
@alexander0042 Looks like there is a server problem. 

Logger: homeassistant.config_entries
Source: config_entries.py:1133
First occurred: 23:38:02 (2 occurrences)
Last logged: 23:39:10

Config entry 'PirateWeather' for pirateweather integration not ready yet: 502, message='Bad Gateway', url=URL('https://api.pirateweather.net/forecast/7cK7GnUK7Z93nZikmEBuVaU43ejP0I0WsosvwxFf/46.42938954957045,26.409193575382236?units=si'); Retrying in background

**Comment by alexander0042** [comment]
Apologies for this- in trying to improve the temperature min/max values(<https://github.com/alexander0042/pirateweather/issues/5>), I ended up introducing a new bug when it was almost, but not quite midnight! Corrected and should be working again now!

**Comment by smarthomefamilyverrips** [comment]
@alexander0042 Yes working now! No problem I just reported in case did go unnoticed 😊

**Comment by alexander0042** [comment]
Great! Happy it's working again, and let me know if you run into any other issues
