### ISSUE TITLE
error with forecast_days_type:

### ISSUE THREAD

**Issue by hunstad** [alexander0042/pirate-weather-ha#85]
# Thanks for the great work!

---
### I restarted my HA this morning and I saw this "warning"  in the log:

    This error originated from a custom integration.

    Logger: custom_components.pirateweather
    Source: custom_components/pirateweather/__init__.py:77 
    Integration: Pirate Weather (documentation, issues) 
    First occurred: 10:16:11 AM (1 occurrences)  
    Last logged: 10:16:11 AM

    forecast_days_type: <class 'str'>
---
### Additional details:
  - version of pirate weather downloaded:  v1.1.0
  - configuration settings if needed:
      - Weather Entity and/or Sensor Entity: both checked
      - Forecast mode: daily
      - Daily forecast: 0,1,2,3,4,5
      - Hourly forecast: none
      - Units: us
      - Round: no

**Comment by alexander0042** [comment]
HI,

Thanks for pointing this out! I've actually already fixed it in the code, but was waiting to see if there were any other issues before pushing a new version out. Nothing seems to have cropped up, so I should be able to get it released shortly!
