### ISSUE TITLE
Weird 500 Error

### ISSUE THREAD

**Issue by Spankythemusical** [alexander0042/pirate-weather-ha#87]
I have installed the integration via HACS and then via the Integrations page.  Tried to configure it the way I want, but then deleted and installed again with bare-minimum default configuration.  When it loads, it shows on the Integrations page as the following:

"Retrying setup: 500, message='Internal Server Error', url=URL('https://api.pirateweather.net/forecast/I'd%20be%20lying%20if%20I%20said%20I%20didn't%20do%20that%20religously.%20Its%20been%20a%20long%20week%20for%20sure!%20That%20info%20is%20definitley%20interesting%20to%20see%20though.%20Thanks!/XX.XXXXXXXXX,-XXX.XXXXXXXXX?units=si')"

All I entered was my API key, long/lat was entered automatically.  The only thing I changed was Round values to the nearest integer, but I even tried that without changing.

**Comment by cloneofghosts** [comment]
Have you tried again at all after the initial setup? If it's still not working then can you try querying the API in your browser to see if it has the same issue?

It could have been that there was an error with the API when you were trying to setup your HA integration and it has since resolved itself. I tested the API on my end and it worked without any issues.

**Comment by Spankythemusical** [comment]
I just tried it again after leaving it for a few hours.  Still the same weird 500 error.  If I go to https://dev.pirateweather.net/forecast/API_KEY/LAT,LONG?units=us, it works.

Just as a test, I removed the "-" from the LONG, and it worked.  It also put my location as China.  So maybe there's a bug with certain locations?

**Comment by Spankythemusical** [comment]
Hmmm, I just tried with a different lat/long to a different section of the city and it worked.  If I change it back to mine, I get the 500 error again.  I'll just use the working lat/long, as there isn't a huge difference in the weather between the two locations.  Just a weird bug.

**Comment by cloneofghosts** [comment]
@Spankythemusical I wonder if there's an issue with your current location that's causing an issue. I know you found a fix but I'd still recommend reaching out to @alexander0042 to see if he can figure anything out. His email address is [api@alexanderrey.ca](mailto:api@alexanderrey.ca)

**Comment by alexander0042** [comment]
Yes, exactly that! I use a regex parser to extract the locations and return the results, so from time to time something weird happens. If you're ok replying with the location in question, feel free to re-open here, otherwise shoot me an e-mail and I'll take a look!
