### ISSUE TITLE
Wind speed in forecast attribute?

### ISSUE THREAD

**Issue by danlo315** [alexander0042/pirate-weather-ha#91]
Looks like the forecast attributes in HA only have the following sensors:
forecast:
  - datetime: '2023-03-25T20:00:00+00:00'
    precipitation_probability: 88
    condition: rainy
    temperature: 38
    precipitation: 0.02

Is there any way to add wind speed to this?  I do a calculation to come up with wind chill (https://www.weather.gov/epz/wxcalc_windchill) and graph out the forecasts.

Thanks!

**Comment by fenty17** [comment]
I was also looking for this. Worked out it's easy enough to add by copying lines 348-349 in weather.py and paste after line 366. Works for me, but unsure if this is something @alexander0042  would want to add into the next release. Living in a windy part of the world, wind forecast is very important for me!
