### ISSUE TITLE
Wanted: Extended human language summary for daily weather

### ISSUE THREAD

**Issue by Spirituss** [alexander0042/pirate-weather-ha#94]
It would be great to add the sensor.daily_summary, which provides extended human language (for **different languages**!) weather summary for the day, as Darksky does. For example, Darksky now shows "Cloudy. Light snow possible in the morning", while Pirateweather just shows "Fog". This is the most interesting info option that is strictly necessary every day.

**Comment by cloneofghosts** [comment]
The good news is that the text summaries are next up on the [roadmap](https://pirateweather.net/en/latest/roadmap/) and the dev is going to use their [existing repoistory](https://github.com/alexander0042/translations) to add in that functionality. There currently is no ETA on when it will be added unfortunately.
