### ISSUE TITLE
Wind speed sensors - missing device_class attribute

### ISSUE THREAD

**Issue by rds76** [alexander0042/pirate-weather-ha#96]
Wind spped sensors are created with default `m/s` with no ability to change UOM due to missing `device_class`. Wind gust sesnors are OK.

**Comment by alexander0042** [comment]
Great catch, and thanks for pointing this out! I just pushed a commit that corrects this, and it'll be live in the next release. 
Let me know if you run into any other issues, and thanks again for using this API
