### ISSUE TITLE
Dead URLs in Installation Guide

### ISSUE THREAD

**Issue by coooooooooosh** [alexander0042/pirate-weather-ha#97]
First off, thank you for building this - incredibly cool project!

Minor issue on the github landing page: Step 4 in HACS installation and Step 8 in Manual installation point to `https://pirateweather.net/apis`, which gives a 404 error. I assume you want this to go somewhere on `https://pirate-weather.apiable.io` (maybe `/products`?) since that is where you can actually subscribe now.

**Comment by alexander0042** [comment]
Great catch here, thank you for posting! I'll give this an edit and push out a new version shortly
