### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by manjulapra** [alexander0042/pirate-weather-ha#98]
I created the API key like it was indicated. FYI the Pirate Weather site has changed. There is no Beta option but a Free option with monthly invoicing. Got the API key after subscribing to the free tier, and the integration keeps saying, "Invalid API Key." I regenerated the API key several times, but it didn't work. 
Integration V 1.1.1
Home Assistant 2023.4.0

**Comment by thekingraptor** [comment]
I'm having the same issue

2023-04-05 23:14:49.585 WARNING (MainThread) [custom_components.pirateweather.config_flow] {'base': 'Invalid API Key, Ensure that the subscribe button is clicked for this endpoint: https://pirateweather.net/apis/hv9nrw1tjg/Beta'}

The key format is _0XXXXXX_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX18 if that is helpful

**Comment by sebastianrasor** [comment]
I'm having the same issue as well.

**Comment by b0mbays** [comment]
Same issue here. 

`Invalid API Key, Ensure that the subscribe button is clicked for this endpoint: https://pirateweather.net/apis/hv9nrw1tjg/Beta`

**Comment by Winni66** [comment]
I have also the same issue !

**Comment by jlbphotos** [comment]
same issue :(

**Comment by tiaanv** [comment]
same issue

**Comment by Winni66** [comment]
Yes, it's a global issue, didn't recognize that this is for -HA repository. I'm trying to transfer my old forecast.io gateway to pirateweather.net for EDOMI

**Comment by alexander0042** [comment]
Hi everyone,

Really sorry for the issue here- Apiable had a glitch where no key, and then the wrong key was being displayed. It's all corrected now, so if you log in and take a look everything should be there!

Again, apologies for the issues here, and let me know if anything else comes up
